[2025-06-22T18:41:03.113+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: polygon_data_pipeline.fetch_daily_aggregates manual__2025-06-22T18:41:01.641700+00:00 [queued]>
[2025-06-22T18:41:03.117+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: polygon_data_pipeline.fetch_daily_aggregates manual__2025-06-22T18:41:01.641700+00:00 [queued]>
[2025-06-22T18:41:03.118+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2025-06-22T18:41:03.125+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_daily_aggregates> on 2025-06-22 18:41:01.641700+00:00
[2025-06-22T18:41:03.127+0000] {standard_task_runner.py:60} INFO - Started process 475 to run task
[2025-06-22T18:41:03.130+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'polygon_data_pipeline', 'fetch_daily_aggregates', 'manual__2025-06-22T18:41:01.641700+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/polygon_data_pipeline.py', '--cfg-path', '/tmp/tmp1mzm_wlr']
[2025-06-22T18:41:03.131+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask fetch_daily_aggregates
[2025-06-22T18:41:03.162+0000] {task_command.py:423} INFO - Running <TaskInstance: polygon_data_pipeline.fetch_daily_aggregates manual__2025-06-22T18:41:01.641700+00:00 [running]> on host 4a3c7287a072
[2025-06-22T18:41:03.204+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='quant-team' AIRFLOW_CTX_DAG_ID='polygon_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_daily_aggregates' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T18:41:01.641700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T18:41:01.641700+00:00'
[2025-06-22T18:41:03.210+0000] {polygon_data_pipeline.py:54} ERROR - Failed to get Polygon API key: 'Variable polygon_api_key does not exist'
[2025-06-22T18:41:03.210+0000] {polygon_data_pipeline.py:55} INFO - Please set 'polygon_api_key' in Airflow Variables (Admin -> Variables)
[2025-06-22T18:41:03.210+0000] {polygon_data_pipeline.py:56} INFO - Get your free API key at: https://polygon.io/
[2025-06-22T18:41:03.211+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/polygon_data_pipeline.py", line 188, in fetch_daily_aggregates
    api_key = get_polygon_api_key()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/polygon_data_pipeline.py", line 49, in get_polygon_api_key
    api_key = Variable.get("polygon_api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable polygon_api_key does not exist'
[2025-06-22T18:41:03.217+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=polygon_data_pipeline, task_id=fetch_daily_aggregates, execution_date=20250622T184101, start_date=20250622T184103, end_date=20250622T184103
[2025-06-22T18:41:03.221+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task fetch_daily_aggregates ('Variable polygon_api_key does not exist'; 475)
[2025-06-22T18:41:03.230+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-22T18:41:03.240+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
